# Generated by Django 4.2.4 on 2023-08-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verifired',
            new_name='is_verified',
        ),
    ]
